#!/bin/bash
. builds/.env-debian

# Clean builds folders
rm "$OUTPUT/$MODULE_NAME.deb" 2> /dev/null
rm -r "$USR" "$ETC" 2> /dev/null

# Create new folders
mkdir "$ETC" "$USR" "$SHARE" "$BIN"

# Copy bin to /usr/bin
cp -r "$SRC_MODULE/bin/"* "$BIN"

# Move private to bin
mv "$BIN/private/"* "$BIN"

# rm private folder
rmdir "$BIN/private"

# Rename files in bin
for f in $(find $BIN -type f); do 
    name=$(basename $f)
    mv -- "$f" "$BIN/$MODULE_NAME-$name" ; 
done
mv "$BIN/$MODULE_NAME-main" "$BIN/$MODULE_NAME"

# Copy config files to /etc 
cp -r "$SRC_MODULE/src" "$ETC/$MODULE_NAME" 
mv "$ANSIBLE_PLAYBOOK.base" "$ANSIBLE_PLAYBOOK"
mv "$ANSIBLE_VARS.base" "$ANSIBLE_VARS"
mv "$ANSIBLE_INVENTORY.base" "$ANSIBLE_INVENTORY"
mv "$VAGRANT_FILE.base" "$VAGRANT_FILE"

# Edit files to install absolute path
for file in $(find $ROOT -not \( -path $ANSIBLE_ROLES -prune \) -type f); do
    # Pattern remplacement
    sed -i "/{ENV_LOCATION}/d" "$file"
    sed -i "s@{MODULE_NAME}@$MODULE_NAME@" "$file"
    sed -i "s@{BIN_PRIVATE}/@$MODULE_NAME-@" "$file"

    # Variable remplacement
    # $HOME
    sed -i "s@\$ANSIBLE_INVENTORY_LOCAL@$ANSIBLE_INVENTORY_LOCAL@" "$file"
    sed -i "s@\$ANSIBLE_PLAYBOOK_LOCAL@$ANSIBLE_PLAYBOOK_LOCAL@" "$file"
    sed -i "s@\$ANSIBLE_VARS_LOCAL@$ANSIBLE_VARS_LOCAL@" "$file"
    sed -i "s@\$VAGRANT_USER_FOLDER@$VAGRANT_USER_FOLDER@" "$file"
    sed -i "s@\$VAGRANT_FILE_LOCAL@$VAGRANT_FILE_LOCAL@" "$file"
    sed -i "s@\$TMP@$TMP@" "$file"
    sed -i "s@\$CONF@$CONF@" "$file"
    sed -i "s@\$HOSTS@$HOSTS@" "$file"
    sed -i "s@\$VBOX@$VBOX@" "$file"
    sed -i "s@\$DEL_VBOX@$DEL_VBOX@" "$file"

    # /etc/module
    sed -i "s@\$ANSIBLE_INVENTORY@$ANSIBLE_INVENTORY@" "$file"
    sed -i "s@\$ANSIBLE_PLAYBOOK@$ANSIBLE_PLAYBOOK@" "$file"
    sed -i "s@\$ANSIBLE_VARS@$ANSIBLE_VARS@" "$file"
    sed -i "s@\$VAGRANT_FILE@$VAGRANT_FILE@" "$file"
done

