#!/bin/bash
. .env

# Package the .deb file
echo "----------- PACKAGING START"

# Clean previous build
rm "$OUTPUT/$MODULE_NAME.rpm" 2> /dev/null
rm -r "$RPM_FOLDER/SOURCES" "$RPM_FOLDER/SRPMS" "$RPM_FOLDER/BUILD"  "$RPM_FOLDER/RPMS" "$RPM_FOLDER/BUILDROOT" 2> /dev/null

# Extract the tar 
cp "$BUILD_OUTPUT" "$RPM_FOLDER"
#tar -C "$RPM_FOLDER/SOURCES" -zxvf "$BUILD_OUTPUT"> /dev/null
#mv "$RPM_FOLDER/SOURCES/build/*" "$RPM_FOLDER/SOURCES"
#rm -r "$RPM_FOLDER/SOURCES/build"

# Package
mkdir "$OUTPUT"  2> /dev/null
rpmbuild --root "$RPM_FOLDER"
if [[ $? -eq 0 ]]; then
    echo "----------- PACKAGING Success"
    cp "$RPM_FOLDER/RPMS/noarch/webserver-deployer.rpm" "$OUTPUT/webserver-deployer.rpm"
else
    echo "----------- PACKAGING ERROR"
    echo "ABORTED."
    exit 1
fi